image: node:latest
stages:
  - prepare
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - npm install
    - npm update --save-dev
  cache:
    paths:
      - node_modules/
      - public/assets/js/
  artifacts:
    paths:
      - node_modules/
      - public/assets/js/
  environment:
    name: staging
  only:
    - develop
    - feature/enviroments

build:
  stage: build
  script:
   - echo "Building the app .."
   - npm install chalk --save-dev
   - npm run build
  only:
   - develop
   - feature/enviroments
   - master


deploy_staging:
  stage: deploy
  variables:
    branch_name: "heroku"
  script:
    - echo "Deploy to staging server"
    - git config --global user.email "jesusant.guerrero@gmail.com"
    - git config --global user.name "Jesus Guerrero"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/ic-payment-staging.git
    - git checkout -b $branch_name
    - echo "!assets/js/"
    - npm run deploy-build
    - git commit --allow-empty -m "Publish to Heroku at $(date)"
    - git push heroku $branch_name:master -f
    - echo "deployed to staging"
  environment:
    name: staging
    url: https://ic-payment-staging.herokuapp.com/
  only:
  - develop
