image: ubuntu
stages:
  - prepare
  - build
  - deploy
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add 
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan payment-plus.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "jesusant.guerrero@gmail.com"
  - git config --global user.name "Jesus Guerrero"
prepare:
  stage: prepare
  script:
    - npm install
    - npm update --save-dev
  cache:
    paths:
      - node_modules/
      - public/assets/js/
  artifacts:
    paths:
      - node_modules/
      - public/assets/js/
  environment:
    name: staging
  only:
    - develop
    - feature/enviroments

build:
  stage: build
  script:
   - echo "Building the app .."
   - npm install chalk --save-dev
   - npm run build
  only:
   - develop
   - feature/enviroments


deploy_staging:
  stage: deploy
  variables:
    branch_name: "heroku"
  script:
    - echo "Deploy to staging server"
    - git remote add do ssh://root@payment-plus.com/home/payment-plus/site.git
    - git push do master -f
    - echo "deployed to staging"
  environment:
    name: staging
    url: http://payment-plus.com/
  only:
  - develop
  - master
